name: s3-deploy

on:
  push:
    branches:
      - main
jobs:    
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 18.x

    - name: Install dependencies
      run: yarn install
      
    - name: Build page
      env:
        VITE_APP_API_URL: ${{secrets.VITE_APP_API_URL}}
      run: yarn build
      
    - name: upload to S3
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync \
        --region ap-northeast-2 \
        dist s3://s3-sohan-bucket \
        --delete
      # working-directory: ./
    
    - name: copy file to EC2 instance via ssh connection
      uses: appleboy/ssh-action@v1.0.0
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
          host: ${{ secrets.AWS_EC2_IP }} # 인스턴스 IP
          username: ${{ secrets.AWS_EC2_USER }} # 우분투 아이디
          key: ${{ secrets.AWS_EC2_PEM_KEY }} # ec2 instance pem key
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
          script: | # 실행할 스크립트
            aws s3 cp s3://s3-sohan-bucket/dist ./ --recursive
            pwd
            ls
      
    
